### ISSUE TITLE
Homepage layout issue on mobile

### ISSUE THREAD

**Issue by etrepum** [MissionBit/missionbit.github.io#83]
The banners and text are overlapping in portrait orientation on my iPhone X

![557114a7-4ba1-4a07-93e2-5a9f532b39ef](https://user-images.githubusercontent.com/26596/38234578-240aee9e-36d3-11e8-8124-cd70f3fbf132.png)

**Comment by juemura** [comment]
Fixed by [PR #84](https://github.com/MissionBit/missionbit.github.io/pull/84)
